In [1]:
import pandas as pd
calgary = pd.read_csv('./data/Civic_Census_by_Ward_and_Dwelling_Structure.csv', sep=';')

In [2]:
calgary.head()

,CENSUS_YEAR,WARD,DWELLING_TYPE,DWELLING_TYPE_CODE,DWELLING_TYPE_DESCRIPTION,DWELLING_CNT,RESIDENT_CNT,OCPD_DWELLING_CNT,VACANT_DWELLING_CNT,OCPD_OWNERSHIP_CNT,RENOVATION_DWELLING_CNT,UNDER_CONST_DWELLING_CNT,INACTIVE_CNT,OTHER_PURPOSE_CNT
0,01/01/2019 12:00:00 AM,1,SINGLE FAMILY HOME,1,A structure originally designed and built to c...,"23,063","67,008","22,559",296,"20,319",59,122,7.0,20.0
1,01/01/2019 12:00:00 AM,1,DUPLEX,2,A structure originally designed and built to c...,"1,959","4,353","1,855",60,"1,118",5,37,1.0,1.0
2,01/01/2019 12:00:00 AM,1,MULTI-PLEX,3,A structure originally designed and built to c...,84,123,65,18,18,0,1,0.0,0.0
3,01/01/2019 12:00:00 AM,1,APARTMENT,4,A structure originally designed and built to c...,"4,741","7,344","4,487",237,"1,714",8,1,3.0,5.0
4,01/01/2019 12:00:00 AM,1,TOWN HOUSE,5,A structure originally designed and built to c...,"3,972","7,832","3,717",149,"2,090",11,89,6.0,0.0

In [3]:
calgary.describe()

,WARD,DWELLING_TYPE_CODE,RENOVATION_DWELLING_CNT,INACTIVE_CNT,OTHER_PURPOSE_CNT
count,3617.000000,3617.000000,3617.000000,3261.000000,2956.000000
mean,7.481615,6.677080,9.573956,12.535725,8.809878
std,3.980839,3.799847,33.020787,44.940633,31.461787
min,1.000000,1.000000,0.000000,0.000000,0.000000
25%,4.000000,3.000000,0.000000,0.000000,0.000000
50%,8.000000,6.000000,0.000000,0.000000,0.000000
75%,11.000000,10.000000,5.000000,4.000000,5.000000
max,14.000000,13.000000,727.000000,626.000000,649.000000

In [4]:
import numpy as np
np.unique(calgary.DWELLING_TYPE)

array(['APARTMENT', 'COMMUNAL HOUSING', 'CONVERTED STRUCTURE', 'DUPLEX',
       'HOTELS, MOTELS  RESIDENCE', 'MANUFACTURED HOME', 'MULTI-PLEX',
       'NURSING HOME, AUXILLARY HOSPITAL LODGE', 'OTHER - INSTITUTIONS',
       'OTHER - RESIDENTIAL', 'RESIDENCE IN COMMERCIAL STRUCTURE',
       'SINGLE FAMILY HOME', 'TOWN HOUSE'], dtype=object)